### ISSUE TITLE
Please fix the section about CPU/NPU

### ISSUE THREAD

**Issue by serjepatoff** [Sab0tag3d/MITM-cheatsheet#2]
"That's when NPUs began to appear, which had a different way of working from general purpose CPUs".

Nope. Network equipment have the same general–purpose CPUs. MIPS or ARM for basic SOHO routers, multicore x86 in more serious boxes. It's the NIC with multiple hardware queues and special methods of NIC<->software communication (explicit ring–buffering, heavy use of DMA) that make a difference. 

Except, of course, for trunk-level equipment with colossal throughput which use FPGAs or ASICs instead of CPUs for packet-level processing (data-plane) plus a CPU just for control purposes (control plane). But I don't think that anyone reading this paper will try to MITM a trunk router.

**Comment by Sab0tag3d** [comment]
Thanks a lot for the explanation! Sorry for the delay.
